# Generated by Django 5.0.2 on 2024-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tasks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
